# Generated by Django 3.2.8 on 2021-10-28 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_materialsandsundries_project_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
