# Generated by Django 3.2.8 on 2021-10-28 14:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0004_project_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
