# Generated by Django 3.2.8 on 2021-11-12 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0005_project_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machine',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='machine',
            name='project_day',
        ),
        migrations.CreateModel(
            name='MachinePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_price_id', models.CharField(max_length=15)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=9)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.machine')),
                ('project_day', models.ManyToManyField(blank=True, to='report.ProjectDay')),
            ],
        ),
    ]
